---
# kubeadm, kubelet, kubectl 설치
- name: Install Kubernetes packages for master
  yum:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Enable and start kubelet
  service:
    name: kubelet
    state: restarted
    enabled: yes

- name: Initialize Kubernetes cluster
  command: >
    kubeadm init 
    --pod-network-cidr=10.244.0.0/16
    --apiserver-advertise-address={{ ansible_default_ipv4.address }}
  register: kubeadm_init
  changed_when: false

- name: Create .kube directory
  file:
    path: /root/.kube
    state: directory
    mode: '0755'

- name: Copy admin.conf to root's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes
    mode: '0600'

# KUBECONFIG 환경변수 설정
- name: Set KUBECONFIG environment variable
  lineinfile:
    path: /root/.bashrc
    line: 'export KUBECONFIG=/etc/kubernetes/admin.conf'
    state: present

# Calico CNI 설치
- name : Install Calico CNI
  ansible.builtin.command:
    cmd : kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml

#- name: Install Calico operator
#  command: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/tigera-operator.yaml
#  changed_when: false
#  ignore_errors: yes

#- name: Install Calico custom resources
#  command: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/custom-resources.yaml
#  changed_when: false
#  ignore_errors: yes

# 조인 명령어 생성
- name: Get join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Save join command to file
  copy:
    content: "{{ join_command.stdout }}"
    dest: /tmp/join.sh
    mode: '0755'

#- name : fetch join cmd file
#  ansible.builtin.fetch:
#    src: /tmp/join.sh
#    dest: /home/ansible/join.sh
#    flat: true
#
#- name: synchronize join.sh to worker
#  ansible.builtin.synchronize:
#    src: /tmp/join.sh
#    dest: /home/ansible/join.sh
#    mode: push
#  delegate_to: node1

- name : fetch join cmd file
  ansible.builtin.fetch:
    src: /tmp/join.sh
    dest: /home/ansible/join.sh
    flat: true

